import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {fabric} from 'fabric';
import {apiJson} from '../../services/apiClient';
import {useEditorStore} from '../../store/useEditorStore';
import {flushProjectSaves,primeProjectSave} from '../../services/projectSaveQueue';
import {CUSTOM_FABRIC_PROPERTIES} from '../../utils/editorElementFactory';
import LocalGenerationPanel, {type GenerationJob,type GenerationResult} from './LocalGenerationPanel';
import {creativeApi} from './creativeApi';
import {createPosterData} from './posterTemplates';
import {POSTER_FORMATS,type Brand,type PosterCopy} from './types';
import '../lesson-video/lesson-video.css';

export default function CreativePosterPanel(){
  const state=useEditorStore(),navigate=useNavigate(),[applyTo,setApplyTo]=useState<'page'|'selected'>('page'),[format,setFormat]=useState('portrait'),[error,setError]=useState('');
  const context=state.creativeContext||{};
  const original=context.poster_copy as PosterCopy;
  const blankCopy:PosterCopy={schema:'creative-poster/v1',family:'product',headline:'',subheadline:'',body:'',cta:'',contact:'',services:[],imagePrompt:''};
  function copyFromCanvas(){const copy={...(original||blankCopy)};for(const object of state.canvas?.getObjects()||[]){const role=object.get('posterRole' as keyof fabric.Object);if(typeof role==='string'&&['headline','subheadline','body','cta','contact'].includes(role)&&'text'in object)Object.assign(copy,{[role]:String((object as fabric.Textbox).text||'')});}return copy;}
  function brandFromSnapshot():Brand|undefined {const snapshot=context.brand_snapshot as (Omit<Brand,'profile_json'|'logos'>&{profile:Brand['profile_json']})|undefined;if(!snapshot)return undefined;const logo=state.canvas?.getObjects().find(object=>object.get('posterRole' as keyof fabric.Object)==='brand-logo') as fabric.Image|undefined;return {...snapshot,profile_json:snapshot.profile||{},logos:logo?[{id:'saved-logo',name:'Saved logo',role:'primary',file_data:logo.getSrc()}]:[]};}
  async function prepare(){state.saveHistory();await flushProjectSaves(state.projectId!);return useEditorStore.getState().projectRevision;}
  function fullDocument(pageData:string){const current=useEditorStore.getState();const pages=current.syncActivePage();const page=JSON.parse(pageData);return JSON.stringify({...page,teckstudioPages:pages.map(p=>p.id===current.activePageId?{...p,data:pageData}:p),teckstudioActivePageId:current.activePageId,teckstudioTimeline:current.timelineProject});}
  async function apply(job:GenerationJob,result:GenerationResult){if(!state.canvas||!state.projectId)return;const revision=await prepare();if(revision!==job.base_revision)throw new Error('Your poster changed after this draft was generated. Regenerate to preserve your edits.');let pageData=JSON.stringify(state.canvas.toJSON(CUSTOM_FABRIC_PROPERTIES));
    if(result.poster){if(applyTo==='selected'){const id=state.selectedObject?.get('id' as keyof fabric.Object);const selected=state.selectedObject as fabric.Textbox|null;if(!id||!selected||!['text','textbox','i-text'].includes(selected.type||''))throw new Error('Select a native text layer before applying selected-text changes.');const role=String(selected.get('posterField' as keyof fabric.Object)||'headline');const value=result.poster[role as keyof PosterCopy];const page=JSON.parse(pageData);page.objects=page.objects.map((object:Record<string,unknown>)=>object.id===id?{...object,text:typeof value==='string'?value:result.poster!.headline}:object);pageData=JSON.stringify(page);}else{const hero=state.canvas.getObjects().find(object=>object.get('posterRole' as keyof fabric.Object)==='hero-image') as fabric.Image|undefined;pageData=await createPosterData({width:state.canvas.getWidth(),height:state.canvas.getHeight(),copy:{...result.poster,contact:copyFromCanvas().contact},brand:brandFromSnapshot(),hero:hero?.getSrc()});}}
    else if(result.asset?.kind==='image'){const source=await creativeApi.dataUrl(result.asset);const image=await new Promise<fabric.Image>((resolve,reject)=>fabric.Image.fromURL(source,object=>object.width?resolve(object):reject(new Error('Unable to open generated artwork.'))));image.set({left:state.canvas.getWidth()/2,top:state.canvas.getHeight()/2,originX:'center',originY:'center',scaleX:Math.min(state.canvas.getWidth()*.7/image.width!,state.canvas.getHeight()*.6/image.height!),scaleY:Math.min(state.canvas.getWidth()*.7/image.width!,state.canvas.getHeight()*.6/image.height!)});image.set({id:`creative-${crypto.randomUUID()}`,posterRole:'hero-image',posterField:'hero-image',name:'Generated artwork'} as Record<string,unknown>);const page=JSON.parse(pageData);const selectedId=applyTo==='selected'?state.selectedObject?.get('id' as keyof fabric.Object):null;page.objects=page.objects.filter((object:Record<string,unknown>)=>!selectedId||object.id!==selectedId);page.objects.push(image.toObject(CUSTOM_FABRIC_PROPERTIES));pageData=JSON.stringify({...page,width:state.canvas.getWidth(),height:state.canvas.getHeight()});}
    else throw new Error('This result cannot be applied to the poster.');
    const data=fullDocument(pageData),before=state.history.slice(0,state.historyIndex+1);const response=await apiJson<{revision:number}>(`/api/creative/jobs/${job.job_id}/apply`,{method:'POST',body:JSON.stringify({expected_revision:revision,data})});await useEditorStore.getState().loadProject(state.projectId);primeProjectSave(state.projectId,response.revision);useEditorStore.setState({history:[...before,data],historyIndex:before.length,projectRevision:response.revision});
  }
  async function reflow(){if(!state.canvas)return;setError('');try{await prepare();const output=POSTER_FORMATS.find(item=>item.id===format)!;const hero=state.canvas.getObjects().find(object=>object.get('posterRole' as keyof fabric.Object)==='hero-image') as fabric.Image|undefined;const data=await createPosterData({width:output.width,height:output.height,copy:copyFromCanvas(),brand:brandFromSnapshot(),hero:hero?.getSrc()});const result=await apiJson<{id:string}>('/api/projects',{method:'POST',body:JSON.stringify({name:`${state.projectName} · ${output.id}`,design_type:'creative-poster',width:output.width,height:output.height,data,creative_context:{...context,poster_format:output.id}})});navigate(`/editor/${result.id}`);}catch(e){setError(e instanceof Error?e.message:'Unable to create reflowed copy.');}}
  return <div className="lv" style={{minHeight:0,padding:12}}><h2>Creative poster</h2><p className="lv-small">Your saved canvas keeps every manual edit. Local AI changes are applied only after review.</p><label className="lv-field">Apply reviewed result to<select value={applyTo} onChange={e=>setApplyTo(e.target.value as 'page'|'selected')}><option value="page">Current page layout / new artwork layer</option><option value="selected">Selected text or artwork layer</option></select></label><p className="lv-small">Replacing the page uses your saved brand and exact contact details. Other pages remain unchanged. Undo restores the previous page.</p>{state.projectId&&<LocalGenerationPanel projectId={state.projectId} kinds={['poster-draft','image']} prepare={prepare} input={(kind,prompt)=>({prompt,...(kind==='poster-draft'?{family:copyFromCanvas().family}:{width:1024,height:1024})})} onApply={apply}/>}<hr/><h3>Create another format</h3><label className="lv-field">Output size<select value={format} onChange={e=>setFormat(e.target.value)}>{POSTER_FORMATS.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><p className="lv-small">Creates a reflowed template copy from labeled text, logo and artwork. Extra hand-placed layers stay in the original project.</p><button onClick={()=>void reflow()}>Reflow as new poster</button>{error&&<p role="alert">{error}</p>}</div>;
}
