import {useEffect,useState} from 'react';
import {apiJson} from '../../services/apiClient';
import {creativeApi} from './creativeApi';
import type {CreativeVideoSpec} from '@teckstudio/lesson-video';
import type {CreativeMedia,PosterCopy} from './types';

export type GenerationKind='poster-draft'|'video-draft'|'image'|'speech'|'transcribe';
export interface GenerationResult {poster?:PosterCopy;spec?:CreativeVideoSpec;asset?:CreativeMedia;cues?:{start:number;end:number;text:string}[]}
export interface GenerationJob {job_id:string;kind:GenerationKind;status:string;stage:string;progress:number;base_revision:number;result?:GenerationResult;error?:string}
type Readiness={worker:{online:boolean};capabilities:Record<string,{ready:boolean;reason?:string;model?:string}>};
const capability:Record<GenerationKind,string>={'poster-draft':'text','video-draft':'text',image:'image',speech:'speech',transcribe:'transcribe'};
const labels:Record<GenerationKind,string>={'poster-draft':'Draft poster copy','video-draft':'Draft a storyboard',image:'Generate artwork',speech:'Generate narration',transcribe:'Time captions from narration'};

function MediaPreview({asset}:{asset:CreativeMedia}){const [url,setUrl]=useState('');useEffect(()=>{let active=true,local='';creativeApi.blob(asset).then(blob=>{local=URL.createObjectURL(blob);if(active)setUrl(local);else URL.revokeObjectURL(local);}).catch(()=>{});return()=>{active=false;if(local)URL.revokeObjectURL(local);};},[asset]);return asset.kind==='audio'?<audio controls src={url} style={{width:'100%'}}/>:<img src={url} alt="Generated artwork awaiting review" style={{width:'100%',maxHeight:250,objectFit:'contain'}}/>;}

export default function LocalGenerationPanel({projectId,kinds,prepare,input,onApply}:{projectId:string;kinds:GenerationKind[];prepare:()=>Promise<number>;input:(kind:GenerationKind,prompt:string)=>Record<string,unknown>;onApply:(job:GenerationJob,result:GenerationResult)=>Promise<void>}){
  const [readiness,setReadiness]=useState<Readiness|null>(null),[jobs,setJobs]=useState<GenerationJob[]>([]),[kind,setKind]=useState<GenerationKind>(kinds[0]),[prompt,setPrompt]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<Record<string,GenerationResult>>({});
  const active=jobs.some(job=>['queued','processing'].includes(job.status));
  useEffect(()=>{let live=true;apiJson<Readiness>('/api/creative/readiness',{timeoutMs:20000}).then(value=>{if(live)setReadiness(value);}).catch(e=>{if(live)setError(e.message);});apiJson<{items:GenerationJob[]}>(`/api/creative/jobs?project_id=${projectId}`).then(value=>{if(live)setJobs(value.items);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[projectId]);
  useEffect(()=>{if(!active)return;const timer=setInterval(()=>{void apiJson<{items:GenerationJob[]}>(`/api/creative/jobs?project_id=${projectId}`).then(value=>setJobs(value.items)).catch(e=>setError(e.message));},2500);return()=>clearInterval(timer);},[active,projectId]);
  async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Local generation failed.');}finally{setBusy(false);}}
  const ready=readiness?.capabilities[capability[kind]];
  return <section className="lv-metadata" style={{padding:12,border:'1px solid #becfc4',borderRadius:10,marginTop:15}}><h3>Local AI assistance</h3><p className="lv-small">Generate a draft, review it, then apply. Your current work stays editable.</p><label className="lv-field">Task<select value={kind} onChange={e=>setKind(e.target.value as GenerationKind)}>{kinds.map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label>{!['speech','transcribe'].includes(kind)&&<label className="lv-field">Describe your idea<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={12000} placeholder="Audience, message, visual style and desired outcome"/></label>}<p className="lv-small">{ready?.ready ? `${ready.model||'Local model'} ready · ${readiness?.worker.online?'worker online':'worker offline'}` : ready?.reason || 'Checking local models…'}</p><button disabled={busy||!ready?.ready||(!prompt.trim()&&!['speech','transcribe'].includes(kind))} onClick={()=>void run(async()=>{const revision=await prepare();const result=await apiJson<GenerationJob>('/api/creative/jobs',{method:'POST',body:JSON.stringify({project_id:projectId,expected_revision:revision,kind,idempotency_key:crypto.randomUUID(),input:input(kind,prompt)})});setJobs(current=>[result,...current.filter(job=>job.job_id!==result.job_id)]);})}>{busy?'Working…':labels[kind]}</button><button disabled={busy} onClick={()=>void run(async()=>{setReadiness(await apiJson('/api/creative/readiness',{timeoutMs:20000}));setJobs((await apiJson<{items:GenerationJob[]}>(`/api/creative/jobs?project_id=${projectId}`)).items);})}>Refresh status</button>
    {error&&<p className="lv-error" role="alert">{error}</p>}
    {jobs.map(job=>{const result=review[job.job_id]||job.result;return <article key={job.job_id} style={{marginTop:18,borderTop:'1px solid #cbd4cb',paddingTop:12}}><strong>{labels[job.kind]} · {job.status}</strong><p className="lv-small">{job.stage} · {job.progress}% · based on revision {job.base_revision}</p>{job.error&&<p role="alert">{job.error}</p>}{['queued','processing'].includes(job.status)&&<button onClick={()=>void run(async()=>{const value=await apiJson<GenerationJob>(`/api/creative/jobs/${job.job_id}`,{method:'DELETE'});setJobs(current=>current.map(j=>j.job_id===job.job_id?value:j));})}>Cancel</button>}{['failed','cancelled'].includes(job.status)&&<button onClick={()=>void run(async()=>{const revision=await prepare();const value=await apiJson<GenerationJob>(`/api/creative/jobs/${job.job_id}/retry`,{method:'POST',body:JSON.stringify({expected_revision:revision})});setJobs(current=>current.map(j=>j.job_id===job.job_id?value:j));})}>Retry</button>}
      {job.status==='completed'&&result&&<details><summary>Review result</summary>{result.poster&&(['headline','subheadline','body','cta','contact'] as const).map(field=><label className="lv-field" key={field}>{field}<textarea value={result.poster![field]} onChange={e=>setReview({...review,[job.job_id]:{...result,poster:{...result.poster!,[field]:e.target.value}}})}/></label>)}{result.spec&&<><label className="lv-field">Video title<input value={result.spec.title} onChange={e=>setReview({...review,[job.job_id]:{...result,spec:{...result.spec!,title:e.target.value}}})}/></label><ol>{result.spec.scenes.map(scene=><li key={scene.id}><strong>{scene.type} · {'title'in scene?scene.title:scene.prompt}</strong><p className="lv-small">{scene.narration?.text||('body'in scene?scene.body:'subtitle'in scene?scene.subtitle:'')}</p></li>)}</ol><p className="lv-small">Apply this storyboard, then edit every scene in the workspace before rendering.</p></>}{result.asset&&<MediaPreview asset={result.asset}/>} {result.cues&&<ol>{result.cues.map((cue,i)=><li key={i}>{cue.start.toFixed(1)}–{cue.end.toFixed(1)}s · {cue.text}</li>)}</ol>}<button disabled={busy} onClick={()=>void run(()=>onApply(job,result))}>Apply reviewed result</button></details>}
    </article>;})}
  </section>;
}
