#!/usr/bin/env node
// Vendors the icons listed in packages/design-spec/src/icons/required.json from
// @tabler/icons (MIT) and simple-icons (CC0, trademarks remain with owners)
// into a committed TypeScript module, so builds need no icon packages at runtime.
// Re-run after editing required.json:  node scripts/vendor-icons.mjs
import { copyFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = join(root, 'packages/design-spec');
const required = JSON.parse(readFileSync(join(pkg, 'src/icons/required.json'), 'utf8'));

function packageDir(name) {
  const dir = join(root, 'node_modules', name);
  if (!existsSync(join(dir, 'package.json'))) {
    console.error(`${name} is not installed. Run npm install at the repository root.`);
    process.exit(1);
  }
  return dir;
}

const tablerDir = packageDir('@tabler/icons');
const tablerVersion = JSON.parse(readFileSync(join(tablerDir, 'package.json'), 'utf8')).version;
const tablerNodes = JSON.parse(readFileSync(join(tablerDir, 'tabler-nodes-outline.json'), 'utf8'));
const simpleDir = packageDir('simple-icons');
const simpleVersion = JSON.parse(readFileSync(join(simpleDir, 'package.json'), 'utf8')).version;
const simpleData = JSON.parse(readFileSync(join(simpleDir, 'data/simple-icons.json'), 'utf8'));
const simpleBySlug = new Map(simpleData.map((icon) => [icon.slug ?? icon.title.toLowerCase(), icon]));

// Share-alike and unknown licences are rejected to keep exported designs unencumbered.
const ALLOWED_LOGO_LICENSES = new Set(['CC0-1.0', 'MIT', 'Apache-2.0', 'CC-BY-3.0', 'CC-BY-4.0']);
const icons = {};
const missing = [];
const rejected = [];

function tablerPaths(slug) {
  const nodes = tablerNodes[slug];
  if (!nodes) return null;
  return nodes.filter(([tag]) => tag === 'path').map(([, attrs]) => attrs.d);
}

for (const [id, slug] of Object.entries(required.tabler)) {
  const paths = tablerPaths(slug);
  if (!paths) { missing.push(`tabler:${slug}`); continue; }
  icons[id] = { set: 'tabler', slug, style: 'stroke', viewBox: '0 0 24 24', paths, license: 'MIT', trademark: false };
}
for (const [id, slug] of Object.entries(required.tablerBrands)) {
  const paths = tablerPaths(slug);
  if (!paths) { missing.push(`tabler:${slug}`); continue; }
  icons[id] = { set: 'tabler', slug, style: 'stroke', viewBox: '0 0 24 24', paths, license: 'MIT', trademark: true };
}
for (const slug of required.simpleIcons) {
  const data = simpleBySlug.get(slug);
  let svg;
  try { svg = readFileSync(join(simpleDir, 'icons', `${slug}.svg`), 'utf8'); } catch { svg = null; }
  if (!data || !svg) { missing.push(`simple-icons:${slug}`); continue; }
  const license = data.license?.type ?? 'CC0-1.0';
  if (!ALLOWED_LOGO_LICENSES.has(license)) { rejected.push(`simple-icons:${slug} (${license})`); continue; }
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((match) => match[1]);
  icons[`logo:${slug}`] = {
    set: 'simple-icons', slug, style: 'fill', viewBox: '0 0 24 24', paths,
    title: data.title, hex: `#${data.hex}`,
    license, trademark: true,
    ...(license.startsWith('CC-BY') ? { attribution: `${data.title} logo via Simple Icons, ${license}` } : {}),
  };
}

if (rejected.length) {
  console.error(`Icons with licences outside the allowlist:\n  ${rejected.join('\n  ')}`);
  process.exit(1);
}
if (missing.length) {
  console.error(`Missing icon slugs (removed upstream or misspelled):\n  ${missing.join('\n  ')}`);
  process.exit(1);
}

const manifest = {
  generatedBy: 'scripts/vendor-icons.mjs',
  sources: {
    tabler: { package: '@tabler/icons', version: tablerVersion, license: 'MIT', url: 'https://tabler.io/icons' },
    'simple-icons': { package: 'simple-icons', version: simpleVersion, license: 'CC0-1.0', url: 'https://simpleicons.org', note: 'Logos are trademarks of their owners; use them only to refer to the product and never to imply endorsement.' },
  },
  count: Object.keys(icons).length,
};

const body = `// GENERATED by scripts/vendor-icons.mjs — do not edit by hand.
import type { IconDef } from '../../types';

export const ICON_SOURCES = ${JSON.stringify(manifest.sources, null, 2)} as const;

export const ICONS: Record<string, IconDef> = ${JSON.stringify(icons, null, 1)};
`;
writeFileSync(join(pkg, 'src/icons/generated/icons.ts'), body);
writeFileSync(join(pkg, 'src/icons/generated/icons.manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
copyFileSync(join(tablerDir, 'LICENSE'), join(pkg, 'licenses/tabler-icons-LICENSE.txt'));
copyFileSync(join(simpleDir, 'LICENSE.md'), join(pkg, 'licenses/simple-icons-LICENSE.md'));
copyFileSync(join(simpleDir, 'DISCLAIMER.md'), join(pkg, 'licenses/simple-icons-DISCLAIMER.md'));
console.log(`Vendored ${manifest.count} icons (tabler ${tablerVersion}, simple-icons ${simpleVersion}).`);
