import type { DesignTemplate } from './types';

/**
 * Hiring starters: single role, several openings, walk-in drive, internship
 * and employee referral. Company, email and roles are samples; "My business
 * details" puts the real company name in the brand mark.
 */

const BRAND = { name: 'Your Company' };
const LEGAL = 'We are an equal opportunity employer. We never charge candidates a fee.';
const FORMATS = ['linkedin', 'square', 'portrait-4x5', 'story', 'a4'];

export const HIRING_TEMPLATES: DesignTemplate[] = [
  {
    id: 'ds-hire-single-role',
    name: 'We’re hiring: one role',
    description: 'Role, experience, location, work mode, CTC and notice period, with skill chips and how to apply.',
    vertical: 'hiring',
    region: 'india',
    category: 'Job posts',
    tags: ['hiring', 'job', 'job post', 'vacancy', 'opening', 'recruitment', 'careers', 'linkedin', 'developer', 'ctc', 'lpa'],
    outputs: ['poster', 'video'],
    altFormats: FORMATS.filter((f) => f !== 'portrait-4x5'),
    featured: true,
    popularity: 98,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'hire-single-role',
      title: 'We’re hiring',
      format: 'portrait-4x5',
      theme: 'minimal-light',
      locale: 'en-IN',
      brand: BRAND,
      pages: [{
        id: 'p1',
        layout: 'job-posting',
        variant: 'single',
        slots: {
          eyebrow: 'We’re hiring',
          title: 'Senior React Developer',
          subtitle: 'Build the web apps our clients use every day, with a small product team.',
          skills: ['React', 'TypeScript', 'Node.js', 'REST APIs', 'AWS', 'Testing'],
          details: [
            { title: 'Experience', body: '4 – 7 years', icon: 'briefcase' },
            { title: 'Location', body: 'Hyderabad · Hybrid', icon: 'map-pin' },
            { title: 'CTC', body: '₹18 – 25 LPA', icon: 'price-inr' },
            { title: 'Notice period', body: 'Immediate – 30 days', icon: 'hourglass' },
          ],
          cta: 'Apply: careers@example.com',
          tag: '#Hiring',
          legal: LEGAL,
        },
        notes: 'We are hiring a senior React developer in Hyderabad, hybrid, four to seven years of experience.',
      }],
    },
  },
  {
    id: 'ds-hire-openings',
    name: 'Multiple openings',
    description: 'Up to eight open roles with experience and location, one apply line. Also works as a LinkedIn carousel page.',
    vertical: 'hiring',
    region: 'india',
    category: 'Job posts',
    tags: ['hiring', 'openings', 'vacancies', 'jobs', 'multiple roles', 'recruitment', 'careers', 'linkedin'],
    outputs: ['poster', 'video'],
    altFormats: FORMATS.filter((f) => f !== 'portrait-4x5'),
    featured: true,
    popularity: 97,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'hire-openings',
      title: 'Open roles',
      format: 'portrait-4x5',
      theme: 'corporate-navy',
      locale: 'en-IN',
      brand: BRAND,
      pages: [{
        id: 'p1',
        layout: 'job-posting',
        variant: 'openings',
        slots: {
          eyebrow: 'Join our team',
          title: '6 open roles',
          subtitle: 'Hyderabad and Bengaluru · Hybrid',
          roles: [
            { title: 'Java Full Stack Developer', body: '5 – 8 yrs · Hyderabad' },
            { title: 'Data Engineer', body: '3 – 6 yrs · Bengaluru' },
            { title: 'DevOps Engineer', body: '4 – 7 yrs · Hyderabad' },
            { title: 'QA Automation Engineer', body: '3 – 5 yrs · Hyderabad' },
            { title: 'UI/UX Designer', body: '2 – 4 yrs · Bengaluru' },
            { title: 'Business Analyst', body: '4 – 6 yrs · Hyderabad' },
          ],
          cta: 'Send your resume: careers@example.com',
          tag: '#Hiring',
        },
        notes: 'We have six open roles across Hyderabad and Bengaluru.',
      }],
    },
  },
  {
    id: 'ds-hire-walk-in',
    name: 'Walk-in drive',
    description: 'Walk-in interview with date, time, venue and eligibility. Prints on A4 for notice boards.',
    vertical: 'hiring',
    region: 'india',
    category: 'Walk-ins',
    tags: ['walk-in', 'walkin', 'interview', 'drive', 'freshers', 'bpo', 'customer support', 'hiring', 'jobs'],
    outputs: ['poster', 'video'],
    altFormats: FORMATS.filter((f) => f !== 'square'),
    popularity: 95,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'hire-walk-in',
      title: 'Walk-in drive',
      format: 'square',
      theme: 'bazaar',
      locale: 'en-IN',
      brand: BRAND,
      pages: [{
        id: 'p1',
        layout: 'job-posting',
        variant: 'single',
        slots: {
          eyebrow: 'Walk-in drive',
          title: 'Customer Support Executive (Voice)',
          skills: ['English', 'Telugu or Hindi', 'Freshers welcome'],
          details: [
            { title: 'Date', body: 'Sat, 17 October', icon: 'calendar' },
            { title: 'Time', body: '10 AM – 3 PM', icon: 'clock' },
            { title: 'Venue', body: 'Madhapur, Hyderabad', icon: 'map-pin' },
            { title: 'Eligibility', body: 'Any graduate', icon: 'school' },
          ],
          cta: 'Bring your resume and an ID proof',
          tag: 'No fee',
        },
        notes: 'Walk-in drive this Saturday from ten to three in Madhapur. Freshers are welcome.',
      }],
    },
  },
  {
    id: 'ds-hire-internship',
    name: 'Internship',
    description: 'Internship or fresher programme with stipend, duration, mode and skills.',
    vertical: 'hiring',
    region: 'india',
    season: { months: [1, 2, 3], label: 'Internship season' },
    category: 'Internships',
    tags: ['internship', 'intern', 'freshers', 'students', 'campus', 'stipend', 'hiring'],
    outputs: ['poster', 'video'],
    altFormats: FORMATS.filter((f) => f !== 'portrait-4x5'),
    popularity: 93,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'hire-internship',
      title: 'Internship',
      format: 'portrait-4x5',
      theme: 'tech-blue',
      locale: 'en-IN',
      brand: BRAND,
      pages: [{
        id: 'p1',
        layout: 'job-posting',
        variant: 'single',
        slots: {
          eyebrow: 'Summer internship 2027',
          title: 'Software Engineering Intern',
          subtitle: 'Work on real projects with a mentor. Strong interns get a full-time offer.',
          skills: ['Python', 'SQL', 'Git', 'Problem solving'],
          details: [
            { title: 'Stipend', body: '₹15,000 / month', icon: 'cash' },
            { title: 'Duration', body: '3 months', icon: 'hourglass' },
            { title: 'Mode', body: 'On-site · Hyderabad', icon: 'laptop' },
            { title: 'Who', body: '2027 & 2028 graduates', icon: 'school' },
          ],
          cta: 'Apply by 31 March: careers@example.com',
          tag: '#Internship',
        },
      }],
    },
  },
  {
    id: 'ds-hire-referral',
    name: 'Employee referral',
    description: 'Ask your team to refer friends, with the bonus, eligible roles and how to refer.',
    vertical: 'hiring',
    region: 'india',
    category: 'Referrals',
    tags: ['referral', 'refer', 'refer and earn', 'bonus', 'employees', 'internal', 'hiring'],
    outputs: ['poster', 'video'],
    altFormats: FORMATS.filter((f) => f !== 'square'),
    popularity: 90,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'hire-referral',
      title: 'Refer and earn',
      format: 'square',
      theme: 'green-growth',
      locale: 'en-IN',
      brand: BRAND,
      pages: [{
        id: 'p1',
        layout: 'job-posting',
        variant: 'single',
        slots: {
          eyebrow: 'Employee referral',
          title: 'Know a great engineer? Refer & earn ₹25,000',
          details: [
            { title: 'Bonus', body: '₹25,000 per hire', icon: 'gift' },
            { title: 'Paid', body: 'After 90 days', icon: 'calendar' },
            { title: 'Roles', body: 'All tech roles', icon: 'briefcase' },
            { title: 'How', body: 'Share resume with HR', icon: 'user-plus' },
          ],
          cta: 'Refer on the HR portal or email hr@example.com',
        },
      }],
    },
  },
];
