import type { DesignTemplate } from './types';

/**
 * Starters written for Indian audiences: festival greetings, shop offers,
 * menus, admissions, invitations and ₹ / BHK / RERA property marketing.
 * Names, phone numbers and addresses are samples to be replaced.
 */

const PHONE = '+91 90000 12345';
const AGENT = { name: 'Priya Reddy', title: 'Property consultant', phone: PHONE, email: 'priya@example.com' };
const RERA = 'RERA Reg. No.: add yours here · Price excl. registration & GST';
const GREETING_FORMATS = ['square', 'portrait-4x5', 'story', 'a4', 'linkedin'];
const OFFER_FORMATS = ['portrait-4x5', 'square', 'story', 'a4', 'a3'];
const INVITE_FORMATS = ['portrait-4x5', 'story', 'a4', 'square'];

interface GreetingInput {
  id: string;
  name: string;
  theme: string;
  format?: string;
  variant?: 'centered' | 'photo';
  eyebrow: string;
  title: string;
  message: string;
  months?: number[];
  season?: string;
  tags: string[];
  featured?: boolean;
  popularity: number;
}

function greeting(input: GreetingInput): DesignTemplate {
  const format = input.format ?? 'square';
  return {
    id: `ds-in-${input.id}`,
    name: input.name,
    description: `${input.variant === 'photo' ? 'Photo greeting' : 'Greeting'} with your shop or family name and contact line, ready for WhatsApp status and Instagram.`,
    vertical: 'festival',
    region: 'india',
    season: input.months ? { months: input.months, label: input.season ?? input.name } : undefined,
    category: 'Festival greetings',
    tags: ['festival', 'greeting', 'wishes', 'whatsapp', 'india', ...input.tags],
    outputs: ['poster', 'video'],
    altFormats: GREETING_FORMATS.filter((f) => f !== format),
    featured: input.featured,
    popularity: input.popularity,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: `in-${input.id}`,
      title: input.name,
      format,
      theme: input.theme,
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'festival-greeting',
        variant: input.variant ?? 'centered',
        slots: {
          eyebrow: input.eyebrow,
          title: input.title,
          message: input.message,
          ...(input.variant === 'photo' ? { image: { src: '', alt: input.name } } : {}),
          sender: 'Sri Lakshmi Jewellers',
          contact: `Main Road, Vijayawada · ${PHONE}`,
        },
        notes: `${input.title}! ${input.message}`,
      }],
    },
  };
}

export const INDIA_FESTIVALS: DesignTemplate[] = [
  greeting({ id: 'diwali', name: 'Diwali wishes', theme: 'diwali-night', eyebrow: 'Wishing you and your family a', title: 'Happy Diwali', message: 'May the festival of lights fill your home with joy, good health and prosperity.', months: [10, 11], season: 'Diwali', tags: ['diwali', 'deepavali', 'lights', 'diya'], featured: true, popularity: 99 }),
  greeting({ id: 'sankranti', name: 'Sankranti & Pongal wishes', theme: 'marigold', format: 'portrait-4x5', variant: 'photo', eyebrow: 'Happy', title: 'Sankranti & Pongal', message: 'Wishing you a sweet harvest season full of kites, kolams and family time.', months: [1], season: 'Sankranti / Pongal', tags: ['sankranti', 'makar sankranti', 'pongal', 'lohri', 'harvest', 'telugu', 'tamil'], popularity: 96 }),
  greeting({ id: 'ugadi', name: 'Ugadi wishes', theme: 'rangoli', eyebrow: 'Ugadi & Gudi Padwa wishes', title: 'Happy Ugadi', message: 'May the new year bring fresh beginnings, good health and success to your family.', months: [3, 4], season: 'Ugadi / Gudi Padwa', tags: ['ugadi', 'yugadi', 'gudi padwa', 'new year', 'telugu', 'kannada'], popularity: 93 }),
  greeting({ id: 'holi', name: 'Holi wishes', theme: 'rangoli', format: 'portrait-4x5', eyebrow: 'Play safe, spread colours', title: 'Happy Holi', message: 'May your life be as colourful and joyful as the festival itself.', months: [3], season: 'Holi', tags: ['holi', 'colours', 'rang'], popularity: 90 }),
  greeting({ id: 'onam', name: 'Onam wishes', theme: 'kasavu', format: 'portrait-4x5', eyebrow: 'Onashamsakal', title: 'Happy Onam', message: 'May King Mahabali’s visit bring prosperity, joy and a grand sadya to every home.', months: [8, 9], season: 'Onam', tags: ['onam', 'kerala', 'malayalam', 'sadya', 'pookalam'], popularity: 92 }),
  greeting({ id: 'independence-day', name: 'Independence Day', theme: 'tiranga', eyebrow: 'Proud to be Indian', title: 'Happy Independence Day', message: 'Saluting the spirit of freedom, unity and every hero who made it possible. Jai Hind!', months: [8], season: 'Independence Day', tags: ['independence day', '15 august', 'tricolour', 'national', 'patriotic'], featured: true, popularity: 95 }),
  greeting({ id: 'republic-day', name: 'Republic Day', theme: 'tiranga', format: 'portrait-4x5', eyebrow: 'Celebrating our Constitution', title: 'Happy Republic Day', message: 'Honouring the Constitution that unites and guides our nation. Jai Hind!', months: [1], season: 'Republic Day', tags: ['republic day', '26 january', 'tricolour', 'national', 'patriotic'], popularity: 91 }),
  greeting({ id: 'ganesh-chaturthi', name: 'Ganesh Chaturthi wishes', theme: 'marigold', format: 'portrait-4x5', variant: 'photo', eyebrow: 'Wishing you a blessed', title: 'Ganesh Chaturthi', message: 'May Lord Ganesha remove every obstacle and bless your family with wisdom and joy.', months: [8, 9], season: 'Ganesh Chaturthi', tags: ['ganesh chaturthi', 'vinayaka chavithi', 'ganpati', 'ganesha'], popularity: 94 }),
  greeting({ id: 'bathukamma', name: 'Bathukamma wishes', theme: 'rangoli', format: 'portrait-4x5', eyebrow: 'Celebrating Telangana’s festival of flowers', title: 'Happy Bathukamma', message: 'May the colours of Bathukamma fill your life with happiness and togetherness.', months: [9, 10], season: 'Bathukamma', tags: ['bathukamma', 'telangana', 'telugu', 'flowers'], popularity: 88 }),
  greeting({ id: 'dussehra', name: 'Dussehra & Navratri wishes', theme: 'diwali-night', format: 'portrait-4x5', eyebrow: 'Navratri, Durga Puja & Vijayadashami', title: 'Happy Dussehra', message: 'May the victory of good over evil inspire you every day of the year.', months: [9, 10], season: 'Dussehra / Durga Puja', tags: ['dussehra', 'dasara', 'navratri', 'durga puja', 'vijayadashami'], popularity: 93 }),
  greeting({ id: 'eid', name: 'Eid Mubarak', theme: 'kasavu', eyebrow: 'Warm wishes on', title: 'Eid Mubarak', message: 'May this Eid bring peace, happiness and togetherness to you and your loved ones.', tags: ['eid', 'eid ul fitr', 'bakrid', 'ramzan', 'ramadan'], popularity: 90 }),
  greeting({ id: 'christmas', name: 'Christmas wishes', theme: 'shaadi-maroon', eyebrow: 'Season’s greetings', title: 'Merry Christmas', message: 'Wishing you joy, peace and a bright New Year ahead.', months: [12], season: 'Christmas', tags: ['christmas', 'xmas', 'new year'], popularity: 89 }),
];

export const INDIA_BUSINESS: DesignTemplate[] = [
  {
    id: 'ds-in-diwali-sale',
    name: 'Festive sale offer',
    description: 'Offer badge, product photo and prices in ₹, with validity, address and phone.',
    vertical: 'business',
    region: 'india',
    season: { months: [10, 11], label: 'Diwali' },
    category: 'Festive offers',
    tags: ['sale', 'offer', 'discount', 'diwali', 'dhamaka', 'shop', 'saree', 'india'],
    outputs: ['poster', 'video'],
    altFormats: OFFER_FORMATS.filter((f) => f !== 'portrait-4x5'),
    featured: true,
    popularity: 98,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-diwali-sale',
      title: 'Festive sale',
      format: 'portrait-4x5',
      theme: 'marigold',
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'offer-promo',
        variant: 'burst',
        slots: {
          eyebrow: 'Diwali Dhamaka sale',
          title: 'Sri Lakshmi Silks',
          subtitle: 'Kanchipuram, Banarasi and Pochampally sarees for the festive season',
          offer: 'Up to 40% off',
          image: { src: '', alt: 'Silk sarees' },
          items: [
            { title: 'Kanchipuram silk', body: 'from ₹4,999' },
            { title: 'Banarasi silk', body: 'from ₹3,499' },
            { title: 'Pochampally ikat', body: 'from ₹2,199' },
            { title: 'Kids ethnic wear', body: 'from ₹799' },
          ],
          validity: 'Offer valid till 2 November',
          address: '12 Gandhi Road, Vijayawada',
          phone: PHONE,
          terms: '*T&C apply. Selected items only.',
        },
        notes: 'Diwali Dhamaka at Sri Lakshmi Silks: up to forty percent off silk sarees, till the second of November.',
      }],
    },
  },
  {
    id: 'ds-in-grand-opening',
    name: 'Grand opening',
    description: 'Announce a new shop with an opening offer, what you sell, date and address.',
    vertical: 'business',
    region: 'india',
    category: 'Shop launch',
    tags: ['grand opening', 'inauguration', 'new shop', 'launch', 'supermarket', 'kirana', 'india'],
    outputs: ['poster', 'video'],
    altFormats: OFFER_FORMATS.filter((f) => f !== 'square'),
    popularity: 92,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-grand-opening',
      title: 'Grand opening',
      format: 'square',
      theme: 'bazaar',
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'offer-promo',
        variant: 'burst',
        slots: {
          eyebrow: 'Grand opening',
          title: 'Annapurna Supermarket',
          offer: 'Free gift on ₹999+',
          image: { src: '', alt: 'Store front' },
          items: [
            { title: 'Fresh vegetables', body: 'Daily' },
            { title: 'Home delivery', body: 'Free above ₹499' },
            { title: 'Groceries & staples', body: 'Best prices' },
          ],
          validity: 'Friday, 6 November · 10 AM',
          address: 'Plot 7, Ring Road, Guntur',
          phone: PHONE,
        },
        notes: 'Annapurna Supermarket opens this Friday. Free gift on every purchase above nine hundred and ninety-nine rupees.',
      }],
    },
  },
  {
    id: 'ds-in-tiffin-menu',
    name: 'Tiffin centre menu',
    description: 'Menu board with dotted price rows, a combo offer, timings and address. Prints on A4.',
    vertical: 'business',
    region: 'india',
    category: 'Menus',
    tags: ['menu', 'restaurant', 'tiffin', 'hotel', 'idli', 'dosa', 'south indian', 'price list', 'india'],
    outputs: ['poster', 'video'],
    altFormats: ['a3', 'portrait-4x5', 'story', 'slide-16x9'],
    popularity: 91,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-tiffin-menu',
      title: 'Tiffin menu',
      format: 'a4',
      theme: 'marigold',
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'offer-promo',
        variant: 'menu',
        slots: {
          eyebrow: 'Hot South Indian tiffins',
          title: 'Annapurna Tiffin Centre',
          subtitle: 'Fresh, homestyle breakfast since 1998',
          offer: 'Combo: 2 idli + vada + coffee ₹99',
          items: [
            { title: 'Idli (2 pcs)', body: '₹40' },
            { title: 'Medu vada', body: '₹35' },
            { title: 'Masala dosa', body: '₹70' },
            { title: 'Pesarattu upma', body: '₹80' },
            { title: 'Mysore bajji', body: '₹45' },
            { title: 'Filter coffee', body: '₹25' },
          ],
          validity: 'Open daily 6:30 – 11:30 AM',
          address: 'Opp. RTC Bus Stand, Nellore',
          phone: PHONE,
          terms: 'Prices include GST.',
        },
      }],
    },
  },
  {
    id: 'ds-in-admissions-open',
    name: 'Admissions open',
    description: 'Coaching or tuition admissions: courses, free demo offer, batch dates and contact.',
    vertical: 'education',
    region: 'india',
    season: { months: [3, 4, 5, 6], label: 'Admissions season' },
    category: 'Admissions',
    tags: ['admissions', 'coaching', 'tuition', 'jee', 'neet', 'iit', 'school', 'college', 'classes', 'india'],
    outputs: ['poster', 'video'],
    altFormats: OFFER_FORMATS.filter((f) => f !== 'portrait-4x5'),
    featured: true,
    popularity: 95,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-admissions-open',
      title: 'Admissions open',
      format: 'portrait-4x5',
      theme: 'corporate-navy',
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'offer-promo',
        variant: 'burst',
        slots: {
          eyebrow: 'Admissions open 2027–28',
          title: 'Vidya Coaching Centre',
          subtitle: 'IIT-JEE, NEET and Foundation batches with weekly tests',
          offer: 'Free demo class',
          image: { src: '', alt: 'Students in class' },
          items: [
            { title: 'JEE Main + Advanced', body: 'Class 11 & 12' },
            { title: 'NEET UG', body: 'Class 11 & 12' },
            { title: 'Foundation', body: 'Classes 8 – 10' },
          ],
          validity: 'New batches from 15 April',
          address: 'Brodipet, Guntur',
          phone: PHONE,
          terms: 'Merit scholarships available. Limited seats.',
        },
        notes: 'Admissions are open at Vidya Coaching Centre for JEE, NEET and Foundation batches. Book a free demo class.',
      }],
    },
  },
];

export const INDIA_EVENTS: DesignTemplate[] = [
  {
    id: 'ds-in-wedding-invite',
    name: 'Wedding invitation',
    description: 'Names, muhurtham, reception and venue on a maroon-and-gold card. Share digitally or print.',
    vertical: 'events',
    region: 'india',
    category: 'Invitations',
    tags: ['wedding', 'marriage', 'shaadi', 'pelli', 'kalyanam', 'invitation', 'invite', 'muhurtham', 'india'],
    outputs: ['poster', 'video'],
    altFormats: INVITE_FORMATS.filter((f) => f !== 'portrait-4x5'),
    featured: true,
    popularity: 97,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-wedding-invite',
      title: 'Wedding invitation',
      format: 'portrait-4x5',
      theme: 'shaadi-maroon',
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'event-invite',
        variant: 'classic',
        slots: {
          eyebrow: 'Together with their families',
          title: 'Ananya & Karthik',
          subtitle: 'request the pleasure of your company at their wedding celebrations',
          date: 'Thursday, 10 December 2026',
          time: 'Muhurtham 10:30 AM · Reception 7 PM',
          venue: 'Sri Venkateswara Kalyana Mandapam, Tirupati',
          hosts: 'With best compliments from the Rao and Iyer families',
          rsvp: `RSVP: ${PHONE}`,
        },
        notes: 'Ananya and Karthik invite you to their wedding on the tenth of December in Tirupati.',
      }],
    },
  },
  {
    id: 'ds-in-griha-pravesh',
    name: 'Housewarming (Griha Pravesh)',
    description: 'Griha Pravesham / Gruhapravesam invitation with muhurtham time and new address.',
    vertical: 'events',
    region: 'india',
    category: 'Invitations',
    tags: ['housewarming', 'griha pravesh', 'gruhapravesam', 'new home', 'invitation', 'invite', 'puja', 'india'],
    outputs: ['poster', 'video'],
    altFormats: INVITE_FORMATS.filter((f) => f !== 'portrait-4x5'),
    popularity: 94,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-griha-pravesh',
      title: 'Housewarming invitation',
      format: 'portrait-4x5',
      theme: 'marigold',
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'event-invite',
        variant: 'classic',
        slots: {
          eyebrow: 'Griha Pravesham',
          title: 'Our housewarming ceremony',
          subtitle: 'With the blessings of the Almighty, we request your presence as we enter our new home.',
          date: 'Sunday, 22 November 2026',
          time: 'Muhurtham 7:30 AM · Lunch follows',
          venue: 'Flat 402, Sai Residency, Kondapur, Hyderabad',
          hosts: 'With best compliments from the Reddy family',
          rsvp: `RSVP: ${PHONE}`,
        },
      }],
    },
  },
  {
    id: 'ds-in-naming-ceremony',
    name: 'Naming ceremony',
    description: 'Namakaranam / Barasala invitation with a baby photo.',
    vertical: 'events',
    region: 'india',
    category: 'Invitations',
    tags: ['naming ceremony', 'namakaranam', 'barasala', 'cradle ceremony', 'baby', 'invitation', 'india'],
    outputs: ['poster', 'video'],
    altFormats: INVITE_FORMATS.filter((f) => f !== 'portrait-4x5'),
    popularity: 87,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-naming-ceremony',
      title: 'Naming ceremony',
      format: 'portrait-4x5',
      theme: 'rangoli',
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'event-invite',
        variant: 'photo',
        slots: {
          eyebrow: 'Namakaranam',
          title: 'Our little one’s naming ceremony',
          image: { src: '', alt: 'Baby photo' },
          date: 'Sunday, 13 December 2026',
          time: '11:00 AM onwards',
          venue: 'Home: 3-45 Gandhi Nagar, Warangal',
          hosts: 'Lakshmi & Suresh',
          rsvp: `RSVP: ${PHONE}`,
        },
      }],
    },
  },
];

export const INDIA_REAL_ESTATE: DesignTemplate[] = [
  {
    id: 'ds-in-3bhk-apartment',
    name: '3 BHK apartment for sale',
    description: 'Indian listing: ₹ price, BHK, carpet area, facing, gated-community highlights, RERA line.',
    vertical: 'real-estate',
    region: 'india',
    category: 'Listings',
    tags: ['bhk', '3bhk', 'flat', 'apartment', 'gated community', 'rera', 'vastu', 'for sale', 'real estate', 'india'],
    outputs: ['poster', 'video'],
    altFormats: ['square', 'story', 'a4', 'slide-16x9'],
    featured: true,
    popularity: 97,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-3bhk-apartment',
      title: '3 BHK apartment',
      format: 'portrait-4x5',
      theme: 'estate-modern',
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'listing-hero',
        slots: {
          eyebrow: 'Ready to move',
          hero: { src: '', alt: 'Apartment tower' },
          headline: 'Spacious 3 BHK in a gated community',
          price: '₹1.25 Cr',
          address: 'Sai Residency, Kondapur, Hyderabad',
          facts: { bhk: 3, baths: 3, sqft: 1650, facing: 'East facing' },
          features: ['Clubhouse, pool & gym', 'Vastu compliant', '24×7 security & power backup', '2 covered car parks'],
          agent: AGENT,
          legal: RERA,
        },
        notes: 'A ready-to-move three BHK in Kondapur, east facing, sixteen fifty square feet, at one point two five crore.',
      }],
    },
  },
  {
    id: 'ds-in-open-plots',
    name: 'Open plots launch',
    description: 'DTCP / HMDA approved plot venture: price per sq yd, plot sizes, facing and amenities.',
    vertical: 'real-estate',
    region: 'india',
    category: 'Plots',
    tags: ['plots', 'open plots', 'venture', 'dtcp', 'hmda', 'layout', 'sq yd', 'land', 'real estate', 'india'],
    outputs: ['poster', 'video'],
    altFormats: ['portrait-4x5', 'story', 'a4', 'slide-16x9'],
    popularity: 93,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-open-plots',
      title: 'Open plots',
      format: 'square',
      theme: 'estate-classic',
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'listing-hero',
        slots: {
          eyebrow: 'New launch',
          hero: { src: '', alt: 'Plot layout' },
          headline: 'DTCP-approved open plots',
          price: '₹18,000 / sq yd',
          address: 'Srinivasa Enclave, near ORR, Shadnagar',
          facts: { lot: '150 – 400 sq yd', facing: 'East & North' },
          features: ['Black-top roads', 'Underground drainage', 'Bank loans available'],
          agent: AGENT,
          legal: RERA,
        },
      }],
    },
  },
  {
    id: 'ds-in-site-visit',
    name: 'Weekend site visit',
    description: 'Invite buyers to a site visit with dates, timings, pickup and on-site offers.',
    vertical: 'real-estate',
    region: 'india',
    category: 'Open house',
    tags: ['site visit', 'open house', 'model flat', 'project', 'real estate', 'india'],
    outputs: ['poster', 'video'],
    altFormats: ['square', 'story', 'a4', 'slide-16x9'],
    popularity: 90,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-site-visit',
      title: 'Site visit',
      format: 'portrait-4x5',
      theme: 'estate-luxe',
      locale: 'en-IN',
      pages: [{
        id: 'p1',
        layout: 'open-house',
        slots: {
          eyebrow: 'Site visit',
          hero: { src: '', alt: 'Model flat' },
          date: 'This Saturday & Sunday',
          time: '10 AM – 6 PM · Free pickup',
          address: 'Sai Residency, Kondapur, Hyderabad',
          highlights: ['Model flat ready to view', 'Spot booking offers', 'Home loan desk on site'],
          agent: AGENT,
        },
        notes: 'Visit Sai Residency this weekend, ten to six, with free pickup and spot booking offers.',
      }],
    },
  },
  {
    id: 'ds-in-project-deck',
    name: 'Residential project deck',
    description: 'Four slides: project hero, amenities, location advantages and site visit.',
    vertical: 'real-estate',
    region: 'india',
    category: 'Listing decks',
    tags: ['project', 'launch', 'presentation', 'slides', 'apartment', 'gated community', 'real estate', 'india'],
    outputs: ['deck', 'video'],
    altFormats: ['slide-4x3'],
    popularity: 92,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'in-project-deck',
      title: 'Sai Residency',
      format: 'slide-16x9',
      theme: 'estate-modern',
      locale: 'en-IN',
      pages: [
        {
          id: 'hero',
          layout: 'listing-hero',
          slots: {
            eyebrow: 'Now launching',
            hero: { src: '' },
            headline: '2 & 3 BHK premium apartments',
            price: 'From ₹78 Lakh',
            address: 'Kondapur, Hyderabad',
            facts: { bhk: 3, sqft: 1650, parking: 2, facing: 'East facing' },
            features: ['Gated community', 'Possession Dec 2027'],
            legal: RERA,
          },
          notes: 'Sai Residency: two and three BHK apartments in Kondapur, from seventy-eight lakh.',
        },
        {
          id: 'amenities',
          layout: 'property-feature-grid',
          variant: 'mosaic',
          slots: {
            title: 'Amenities',
            photos: [{ src: '' }, { src: '' }, { src: '' }],
            features: [
              { title: 'Swimming pool', icon: 'pool' },
              { title: 'Gym & clubhouse', icon: 'gym' },
              { title: 'Gated & CCTV', icon: 'shield-check' },
              { title: 'Lifts & power backup', icon: 'elevator' },
            ],
          },
          notes: 'A pool, gym and clubhouse, gated security with CCTV, lifts and full power backup.',
        },
        {
          id: 'location',
          layout: 'concept-cards',
          variant: 'grid',
          slots: {
            title: 'Location advantages',
            cards: [
              { title: 'IT corridor', body: '15 minutes to HITEC City and Gachibowli.', icon: 'building' },
              { title: 'Metro', body: 'Kondapur metro station 5 minutes away.', icon: 'metro' },
              { title: 'Schools', body: 'Three CBSE schools within 2 km.', icon: 'school' },
            ],
          },
          notes: 'Fifteen minutes to HITEC City, five minutes to the metro, and good schools nearby.',
        },
        {
          id: 'visit',
          layout: 'open-house',
          slots: {
            eyebrow: 'Site visit',
            hero: { src: '' },
            date: 'Every Saturday & Sunday',
            time: '10 AM – 6 PM · Free pickup',
            address: 'Kondapur, Hyderabad',
            agent: AGENT,
          },
          notes: 'Book a site visit any weekend; we will pick you up.',
        },
      ],
    },
  },
];

export const INDIA_TEMPLATES: DesignTemplate[] = [...INDIA_FESTIVALS, ...INDIA_BUSINESS, ...INDIA_EVENTS, ...INDIA_REAL_ESTATE];
