import type { DesignTemplate } from './types';

const AGENT = { name: 'Jordan Rivera', title: 'Listing agent', phone: '(555) 010-2030', email: 'jordan@example.com' };
const SOCIAL = ['portrait-4x5', 'square', 'story', 'letter', 'a4', 'slide-16x9'];

export const REAL_ESTATE_STARTERS: DesignTemplate[] = [
  {
    id: 'ds-re-modern-family-home',
    name: 'Modern family home',
    description: 'Listing poster with hero photo, price, beds/baths/sq ft and agent contact.',
    vertical: 'real-estate',
    category: 'Listings',
    tags: ['listing', 'for sale', 'property', 'house', 'real estate'],
    outputs: ['poster', 'video'],
    altFormats: SOCIAL,
    featured: true,
    popularity: 98,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'modern-family-home',
      title: 'Modern family home',
      format: 'portrait-4x5',
      theme: 'estate-modern',
      brand: { name: 'Your Brokerage' },
      pages: [{
        id: 'p1',
        layout: 'listing-hero',
        slots: {
          eyebrow: 'For sale',
          hero: { src: '', alt: 'Front of the house' },
          headline: 'Light-filled family home near parks',
          price: '$749,000',
          address: '24 Maple Grove Lane, Springfield',
          facts: { beds: 4, baths: 3, sqft: 2450 },
          features: ['Open-plan kitchen', 'Two-car garage', 'South-facing garden', 'Walk to schools'],
          agent: AGENT,
        },
        notes: 'Welcome to 24 Maple Grove Lane: four bedrooms, three baths and a south-facing garden, listed at 749 thousand.',
      }],
    },
  },
  {
    id: 'ds-re-open-house',
    name: 'Open house this Sunday',
    description: 'Full-bleed photo with open-house banner, date, time and highlights.',
    vertical: 'real-estate',
    category: 'Open house',
    tags: ['open house', 'event', 'property', 'real estate'],
    outputs: ['poster', 'video'],
    altFormats: SOCIAL,
    featured: true,
    popularity: 95,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'open-house',
      title: 'Open house',
      format: 'square',
      theme: 'estate-classic',
      pages: [{
        id: 'p1',
        layout: 'open-house',
        slots: {
          eyebrow: 'Open House',
          hero: { src: '', alt: 'Living room' },
          date: 'Sunday, 12 October',
          time: '1:00 – 4:00 PM',
          address: '8 Harbour View Road, Bayside',
          highlights: ['3 bedrooms with sea views', 'Renovated kitchen', 'Private terrace'],
          agent: AGENT,
        },
        notes: 'Join us this Sunday from one to four at 8 Harbour View Road.',
      }],
    },
  },
  {
    id: 'ds-re-just-sold',
    name: 'Just sold',
    description: 'Celebrate a closed sale with results stats.',
    vertical: 'real-estate',
    category: 'Just sold',
    tags: ['just sold', 'sold', 'results', 'real estate'],
    outputs: ['poster', 'video'],
    altFormats: SOCIAL,
    popularity: 92,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'just-sold',
      title: 'Just sold',
      format: 'square',
      theme: 'estate-luxe',
      pages: [{
        id: 'p1',
        layout: 'just-sold',
        slots: {
          banner: 'Just Sold',
          hero: { src: '', alt: 'Sold property' },
          address: '112 Cedar Crest Drive',
          price: '$1,280,000',
          stats: [{ value: '6', label: 'Days on market' }, { value: '104%', label: 'Of asking price' }, { value: '9', label: 'Offers received' }],
          agent: AGENT,
        },
        notes: 'Sold in six days at 104 percent of asking, with nine offers.',
      }],
    },
  },
  {
    id: 'ds-re-feature-highlights',
    name: 'Property feature highlights',
    description: 'Photo mosaic plus an icon grid of features, sized for a printed flyer.',
    vertical: 'real-estate',
    category: 'Flyers',
    tags: ['flyer', 'features', 'amenities', 'property', 'real estate'],
    outputs: ['poster'],
    altFormats: ['a4', 'letter', 'portrait-4x5', 'square', 'slide-16x9'],
    popularity: 90,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'feature-highlights',
      title: 'Property feature highlights',
      format: 'a4',
      theme: 'estate-classic',
      pages: [{
        id: 'p1',
        layout: 'property-feature-grid',
        variant: 'mosaic',
        slots: {
          eyebrow: '24 Maple Grove Lane',
          title: 'Made for family life',
          photos: [{ src: '' }, { src: '' }, { src: '' }],
          features: [
            { title: '4 bedrooms', icon: 'bed' },
            { title: '3 bathrooms', icon: 'bath' },
            { title: '2,450 sq ft', icon: 'sqft' },
            { title: 'Two-car garage', icon: 'garage' },
            { title: 'Heated pool', icon: 'pool' },
            { title: 'Mature garden', icon: 'trees' },
          ],
          cta: 'Book a private viewing: (555) 010-2030',
        },
      }],
    },
  },
];

export const REAL_ESTATE_DECKS: DesignTemplate[] = [
  {
    id: 'ds-deck-property-listing',
    name: 'Property listing deck',
    description: 'Five slides: hero listing, features, gallery, neighbourhood and open house.',
    vertical: 'real-estate',
    category: 'Listing decks',
    tags: ['listing', 'presentation', 'slides', 'property tour', 'real estate'],
    outputs: ['deck', 'video'],
    altFormats: ['slide-16x9', 'slide-4x3'],
    featured: true,
    popularity: 97,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'property-listing-deck',
      title: '24 Maple Grove Lane',
      format: 'slide-16x9',
      theme: 'estate-modern',
      brand: { name: 'Your Brokerage' },
      pages: [
        {
          id: 'hero',
          layout: 'listing-hero',
          slots: {
            eyebrow: 'For sale',
            hero: { src: '' },
            headline: 'Light-filled family home near parks',
            price: '$749,000',
            address: '24 Maple Grove Lane, Springfield',
            facts: { beds: 4, baths: 3, sqft: 2450, parking: 2 },
            features: ['Open-plan kitchen', 'South-facing garden'],
          },
          notes: 'Welcome to 24 Maple Grove Lane, a four-bedroom family home listed at 749 thousand.',
        },
        {
          id: 'features',
          layout: 'property-feature-grid',
          variant: 'mosaic',
          slots: {
            title: 'Inside the home',
            photos: [{ src: '' }, { src: '' }, { src: '' }],
            features: [
              { title: 'Chef’s kitchen', icon: 'flame' },
              { title: 'Home office', icon: 'desktop' },
              { title: 'Central air', icon: 'air-conditioning' },
              { title: 'Fast fibre', icon: 'wifi' },
            ],
          },
          notes: 'Inside you will find a chef’s kitchen, a home office, central air and fibre internet.',
        },
        {
          id: 'gallery',
          layout: 'property-feature-grid',
          variant: 'gallery',
          slots: { title: 'Gallery', photos: [{ src: '' }, { src: '' }, { src: '' }, { src: '' }] },
          notes: 'Take a look around.',
        },
        {
          id: 'area',
          layout: 'concept-cards',
          variant: 'grid',
          slots: {
            title: 'The neighbourhood',
            cards: [
              { title: 'Schools', body: 'Two top-rated schools within a 10-minute walk.', icon: 'school' },
              { title: 'Parks', body: 'Maple Grove park and trails at the end of the street.', icon: 'trees' },
              { title: 'Transit', body: 'Station 5 minutes away; 25 minutes to downtown.', icon: 'map-pin' },
            ],
          },
          notes: 'The neighbourhood has great schools, parks at the end of the street, and a station five minutes away.',
        },
        {
          id: 'visit',
          layout: 'open-house',
          slots: {
            hero: { src: '' },
            date: 'Sunday, 12 October',
            time: '1:00 – 4:00 PM',
            address: '24 Maple Grove Lane, Springfield',
            agent: AGENT,
          },
          notes: 'Come see it this Sunday from one to four, or call Jordan to book a private viewing.',
        },
      ],
    },
  },
];
