import type { DesignTemplate } from './types';

const POSTER_FORMATS = ['portrait-4x5', 'square', 'story', 'a4', 'slide-16x9', 'linkedin'];

export const TECH_STARTERS: DesignTemplate[] = [
  {
    id: 'ds-tech-caching-101',
    name: 'What is caching?',
    description: 'Concept explainer with five numbered cards on how a cache speeds up reads.',
    vertical: 'tech',
    category: 'Concept explainers',
    tags: ['caching', 'performance', 'system design', 'backend', 'redis'],
    outputs: ['poster', 'video'],
    altFormats: POSTER_FORMATS,
    featured: true,
    popularity: 98,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'caching-101',
      title: 'What is caching?',
      format: 'portrait-4x5',
      theme: 'tech-blue',
      pages: [{
        id: 'p1',
        layout: 'concept-cards',
        variant: 'numbered',
        slots: {
          eyebrow: 'System design basics',
          title: 'What is caching?',
          subtitle: 'Keep a copy of expensive answers close to where they are needed.',
          cards: [
            { title: 'Cache hit', body: 'The answer is already stored, so it returns in microseconds.', icon: 'bolt' },
            { title: 'Cache miss', body: 'Fetch from the database, return it and store a copy.', icon: 'database' },
            { title: 'TTL', body: 'Entries expire after a time-to-live so data stays fresh.', icon: 'clock' },
            { title: 'Eviction', body: 'When full, drop the least recently used entries first.', icon: 'stack' },
            { title: 'Invalidation', body: 'Delete or update entries whenever the source changes.', icon: 'arrows-exchange' },
          ],
          cta: 'Cache what is read often and changes rarely.',
          tag: '#SystemDesign',
        },
        notes: 'Caching keeps a copy of expensive results close to the reader. Hits are fast, misses go to the database and fill the cache. Expire entries with a TTL, evict the least recently used, and invalidate on writes.',
      }],
    },
  },
  {
    id: 'ds-tech-rag-pipeline',
    name: 'RAG pipeline',
    description: 'Architecture flow of retrieval-augmented generation from documents to answer.',
    vertical: 'tech',
    category: 'Architecture diagrams',
    tags: ['rag', 'llm', 'ai', 'embeddings', 'vector database', 'architecture'],
    outputs: ['poster', 'video'],
    altFormats: ['a4', 'portrait-4x5', 'square', 'slide-16x9', 'story'],
    featured: true,
    popularity: 97,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'rag-pipeline',
      title: 'RAG pipeline',
      format: 'a4',
      theme: 'purple-ai',
      pages: [{
        id: 'p1',
        layout: 'architecture-flow',
        variant: 'flow',
        slots: {
          eyebrow: 'AI engineering',
          title: 'How a RAG pipeline answers',
          subtitle: 'Retrieve relevant context first, then let the model generate a grounded answer.',
          flow: {
            nodes: [
              { id: 'docs', label: 'Documents', icon: 'file-code' },
              { id: 'chunk', label: 'Chunk + embed', icon: 'cpu' },
              { id: 'store', label: 'Vector store', icon: 'database' },
              { id: 'query', label: 'User question', icon: 'chatbot' },
              { id: 'retrieve', label: 'Retrieve top-k', icon: 'search' },
              { id: 'llm', label: 'LLM answer', icon: 'brain' },
            ],
            edges: [
              { from: 'docs', to: 'chunk' },
              { from: 'chunk', to: 'store' },
              { from: 'store', to: 'query' },
              { from: 'query', to: 'retrieve' },
              { from: 'retrieve', to: 'llm' },
            ],
          },
          takeaway: 'Good retrieval matters more than a bigger model.',
        },
        notes: 'Documents are chunked and embedded into a vector store. At question time we retrieve the closest chunks and pass them to the model, which answers using that context.',
      }],
    },
  },
  {
    id: 'ds-tech-list-comprehensions',
    name: 'Python list comprehensions',
    description: 'Code explainer with a snippet and three numbered callouts.',
    vertical: 'tech',
    category: 'Code explainers',
    tags: ['python', 'code', 'beginner', 'syntax'],
    outputs: ['poster', 'video'],
    altFormats: ['square', 'portrait-4x5', 'slide-16x9', 'story'],
    popularity: 93,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'list-comprehensions',
      title: 'Python list comprehensions',
      format: 'square',
      theme: 'green-growth',
      pages: [{
        id: 'p1',
        layout: 'code-explainer',
        variant: 'explainer',
        slots: {
          eyebrow: 'Python in 60 seconds',
          title: 'List comprehensions',
          code: { language: 'python', source: 'prices = [120, 45, 80, 300]\n\n# keep and transform in one line\ndeals = [p * 0.9 for p in prices if p > 50]\n\nprint(deals)  # [108.0, 72.0, 270.0]' },
          callouts: ['Expression first: what each item becomes.', 'Then the loop: where items come from.', 'Optional filter at the end.'],
          takeaway: 'Readable when short; switch to a loop when it grows.',
        },
        notes: 'A list comprehension builds a new list in one expression: first what each item becomes, then the loop, then an optional filter.',
      }],
    },
  },
  {
    id: 'ds-tech-sql-vs-nosql',
    name: 'SQL vs NoSQL',
    description: 'Side-by-side comparison slide with a verdict.',
    vertical: 'tech',
    category: 'Comparisons',
    tags: ['database', 'sql', 'nosql', 'comparison', 'backend'],
    outputs: ['poster', 'video'],
    altFormats: ['slide-16x9', 'square', 'portrait-4x5', 'linkedin', 'story'],
    popularity: 91,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'sql-vs-nosql',
      title: 'SQL vs NoSQL',
      format: 'slide-16x9',
      theme: 'minimal-light',
      pages: [{
        id: 'p1',
        layout: 'comparison',
        slots: {
          eyebrow: 'Choosing a database',
          title: 'SQL vs NoSQL',
          left: { title: 'SQL', points: ['Fixed schema with relations', 'Joins and transactions', 'Scale up, then read replicas', 'Great for money and orders'] },
          right: { title: 'NoSQL', points: ['Flexible documents or key-value', 'Denormalise for your queries', 'Scale out across nodes', 'Great for feeds, events, caches'] },
          verdict: 'Start with SQL unless your access pattern clearly needs otherwise.',
        },
        notes: 'SQL gives you schemas, joins and transactions. NoSQL trades those for flexible data and easy horizontal scaling. Pick based on access patterns.',
      }],
    },
  },
  {
    id: 'ds-tech-git-cheatsheet',
    name: 'Git cheat sheet',
    description: 'Cheat sheet grid of six everyday Git commands.',
    vertical: 'tech',
    category: 'Cheat sheets',
    tags: ['git', 'cheatsheet', 'developer', 'version control'],
    outputs: ['poster'],
    altFormats: ['a4', 'portrait-4x5', 'square', 'slide-16x9'],
    popularity: 90,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'git-cheatsheet',
      title: 'Git cheat sheet',
      format: 'a4',
      theme: 'neon-future',
      pages: [{
        id: 'p1',
        layout: 'code-explainer',
        variant: 'cheatsheet',
        slots: {
          eyebrow: 'Developer essentials',
          title: 'Git cheat sheet',
          snippets: [
            { title: 'Start a branch', body: 'git switch -c feature/login' },
            { title: 'Stage changes', body: 'git add -p' },
            { title: 'Commit', body: 'git commit -m "Add login form"' },
            { title: 'Sync with main', body: 'git fetch origin\ngit merge origin/main' },
            { title: 'Undo last commit', body: 'git reset --soft HEAD~1' },
            { title: 'See history', body: 'git log --oneline --graph' },
          ],
          takeaway: 'Small commits, clear messages, frequent syncs.',
        },
      }],
    },
  },
];

export const TECH_DECKS: DesignTemplate[] = [
  {
    id: 'ds-deck-http-lesson',
    name: 'Tech lesson: How HTTP requests work',
    description: 'Six-slide lesson: title, key ideas, request flow, code, comparison and recap.',
    vertical: 'tech',
    category: 'Lesson decks',
    tags: ['lesson', 'slides', 'http', 'web', 'api', 'teaching'],
    outputs: ['deck', 'video'],
    altFormats: ['slide-16x9', 'slide-4x3'],
    featured: true,
    popularity: 99,
    source: 'starter',
    spec: {
      schema: 'design-spec/v1',
      id: 'http-lesson',
      title: 'How HTTP requests work',
      format: 'slide-16x9',
      theme: 'corporate-navy',
      pages: [
        {
          id: 'title',
          layout: 'concept-cards',
          variant: 'hero',
          slots: {
            eyebrow: 'Web fundamentals · Lesson 1',
            title: 'How HTTP requests work',
            subtitle: 'From typing a URL to seeing a page, in five steps.',
            cards: [{ title: 'Request', icon: 'arrow-right' }, { title: 'Response', icon: 'check' }, { title: 'Status codes', icon: 'checklist' }],
          },
          notes: 'In this lesson we follow one HTTP request from the browser to the server and back.',
        },
        {
          id: 'ideas',
          layout: 'concept-cards',
          variant: 'grid',
          slots: {
            title: 'Four ideas to remember',
            cards: [
              { title: 'Client and server', body: 'The browser asks; a server answers.', icon: 'desktop' },
              { title: 'Methods', body: 'GET reads, POST creates, PUT replaces, DELETE removes.', icon: 'api' },
              { title: 'Headers', body: 'Metadata such as content type, auth and caching rules.', icon: 'settings' },
              { title: 'Status codes', body: '2xx success, 3xx redirect, 4xx client error, 5xx server error.', icon: 'checklist' },
            ],
          },
          notes: 'Keep four ideas in mind: who asks and who answers, the method, the headers and the status code.',
        },
        {
          id: 'flow',
          layout: 'architecture-flow',
          variant: 'steps',
          slots: {
            title: 'One request, step by step',
            flow: {
              nodes: [
                { id: 'url', label: 'Type URL', icon: 'globe' },
                { id: 'dns', label: 'DNS lookup', icon: 'search' },
                { id: 'tls', label: 'TLS handshake', icon: 'lock' },
                { id: 'req', label: 'Send request', icon: 'arrow-right' },
                { id: 'resp', label: 'Render response', icon: 'desktop' },
              ],
              edges: [],
            },
            takeaway: 'Every page load repeats this sequence, often dozens of times.',
          },
          notes: 'The browser resolves the domain with DNS, opens a secure TLS connection, sends the request, and renders the response.',
        },
        {
          id: 'code',
          layout: 'code-explainer',
          variant: 'explainer',
          slots: {
            title: 'What the request looks like',
            code: { language: 'text', source: 'GET /api/courses/42 HTTP/1.1\nHost: example.com\nAccept: application/json\nAuthorization: Bearer <token>\n\nHTTP/1.1 200 OK\nContent-Type: application/json\n\n{"id": 42, "title": "HTTP basics"}' },
            callouts: ['Method + path + version', 'Headers describe the request', 'Status line tells you the outcome', 'Body carries the data'],
          },
          notes: 'Here is a raw request and response. Read the first line, then the headers, then the body.',
        },
        {
          id: 'compare',
          layout: 'comparison',
          slots: {
            title: 'GET vs POST',
            left: { title: 'GET', points: ['Reads data', 'Parameters in the URL', 'Safe to repeat and cache'] },
            right: { title: 'POST', points: ['Creates or submits data', 'Data in the request body', 'Not cached; may change state'] },
            verdict: 'Use GET to read and POST to change things.',
          },
          notes: 'GET is for reading and can be cached. POST sends data in the body and usually changes something on the server.',
        },
        {
          id: 'recap',
          layout: 'concept-cards',
          variant: 'numbered',
          slots: {
            title: 'Recap and practice',
            cards: [
              { title: 'Name the steps', body: 'URL, DNS, TLS, request, response.' },
              { title: 'Read a status code', body: 'What does 404 mean? And 503?' },
              { title: 'Try it', body: 'Open dev tools, Network tab, reload a page.' },
            ],
            cta: 'Next lesson: REST API design',
          },
          notes: 'To recap: name the five steps, read status codes, and inspect real requests in your browser dev tools.',
        },
      ],
    },
  },
];
